apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-deploy-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-deploy-component
    app.kubernetes.io/part-of: e2e-build-deploy
  name: build-deploy-component
  namespace: appstudio-e2e-test
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: build-deploy-component
status:
  loadBalancer: {}
